### ISSUE TITLE
Snakemake standardized usage

### ISSUE THREAD

**Issue by uniqueg** [cbg-ethz/V-pipe#151]
### Problem

V-pipe is [listed](https://snakemake.github.io/snakemake-workflow-catalog?repo=cbg-ethz/V-pipe) in the [Snakemake Workflow Catalog](https://snakemake.github.io/snakemake-workflow-catalog). However, it does not adhere to the [standardized usage](https://snakemake.github.io/snakemake-workflow-catalog?rules=true) and therefore isn't listed in the default view (tab "Standardized usage") and can only be found after manually changing to a different view (tab "All workflows").

Adhering to the recommended standardized usage might increase the exposure of V-pipe, particularly, as the workflow -with the current number of stars- would be featured on the front page.

### Solution

As described [here](https://snakemake.github.io/snakemake-workflow-catalog?rules=true), being listed in the "Standardized usage" section requires:

- [x] the main workflow definition in file `workflow/Snakefile`
- [x] workflow configuration instructions to be provided in `config/README.md`
- [ ] a `.snakemake-workflow-catalog.yml` file to configure usage instructions

As the first two conditions are already fulfilled, it appears that only the last condition needs to be addressed for V-pipe to be listed in the "Standardized usage" section.

### Additional context

The allowed/required sections for the usage instructions configuration file (in YAML format) are described below:

```yaml
usage:
  mandatory-flags: # optional definition of additional flags
    desc: # describe your flags here in a few sentences (they will be inserted below the example commands)
    flags: # put your flags here
  software-stack-deployment: # definition of software deployment method (at least one of conda, singularity, or singularity+conda)
    conda: true # whether pipeline works with --use-conda
    singularity: true # whether pipeline works with --use-singularity
    singularity+conda: true # whether pipeline works with --use-singularity --use-conda
  report: true # add this to confirm that the workflow allows to use 'snakemake --report report.zip' to generate a report containing all results and explanations
```

A working example for a Snakemake Workflow Catalog configuration can be found, e.g., [here](https://github.com/zavolanlab/zarp/blob/ac953471b475b9f1b81ac08679d01fc4c2f98d9d/.snakemake-workflow-catalog.yml) for the [ZARP](https://github.com/zavolanlab/zarp) workflow.
