### ISSUE TITLE
Default deconvolution config is missing

### ISSUE THREAD

**Issue by GeertvanGeest** [cbg-ethz/V-pipe#161]
**Describe the bug**
The default for `deconvolution.config` is `"{VPIPE_BASEDIR}/../resources/cowwid/deconv_linear_logit_quasi_strat.yaml"`. However, this file does not exist in the repository (at least not in the default branch). 

This results in the following error if no deconvolution config is specified:

```
MissingInputException in rule deconvolution in file /Users/geertvangeest/Documents/repositories/test-vpipe/vp-analysis/V-pipe/workflow/rules/signatures.smk, line 309:
Missing input files for rule deconvolution:
    output: results/deconvoluted.tsv.zst, results/deconvoluted_upload.json
    affected files:
        /Users/geertvangeest/Documents/repositories/test-vpipe/vp-analysis/V-pipe/workflow/../resources/cowwid/deconv_linear_logit_quasi_strat.yaml
```

**To Reproduce**

config.yaml:

```yaml
general:
    virus_base_config: 'sars-cov-2'

input:
    samples_file: samples.tsv
    variants_def_directory: vocs/

output:
    samples_file: samples.tsv
    trim_primers: true

tallymut: 
    timeline_file: timeline.tsv
```

V-pipe command:

```bash
./vpipe --cores 8 deconvolution
```

**Expected behavior**
The pipeline runs without failure
